### ISSUE TITLE
Unable to start Minincore

### ISSUE THREAD

**Issue by MiningCryptoLive** [oliverw/miningcore#1039]
I get the following error after starting Minincore.

Using configuration file config.json

[2021-12-14 11:28:07.0112] [I] [Core] Version 64.0.1.0-master [6bdb04206619609eb71068f65cdf6e4a37814d40]
[2021-12-14 11:28:07.0349] [I] [Core] Runtime .NET 6.0.0-rtm.21522.10 on Linux 5.11.0-41-generic #45-Ubuntu SMP Fri Nov 5 11:37:01 UTC 2021 [X64]
[2021-12-14 11:28:07.0436] [I] [Core] Prometheus Metrics 127.0.0.1:4000/metrics
[2021-12-14 11:28:07.0436] [I] [Core] WebSocket notifications streaming 127.0.0.1:4000/notifications
[2021-12-14 11:28:07.5620] [D] [Host] Hosting starting
Autofac.Core.DependencyResolutionException: An exception was thrown while activating λ:Microsoft.Extensions.Hosting.IHostedService[] -> Miningcore.Notifications.NotificationService -> Miningcore.Pushover.PushoverClient.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Miningcore.Configuration.ClusterConfig, System.Net.Http.IHttpClientFactory)' on type 'PushoverClient'.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Pushover.PushoverClient..ctor(ClusterConfig clusterConfig, IHttpClientFactory httpClientFactory) in /home/etcpool/miningcore/src/Miningcore/Pushover/PushoverClient.cs:line 13
   at lambda_method162(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Miningcore.Program.Main(String[] args) in /home/etcpool/miningcore/src/Miningcore/Program.cs:line 201
Cluster cannot start. Good Bye!

Here's my config.json

{
"logging": {
"level": "debug",
"enableConsoleLog": true,
"enableConsoleColors": true,
"logFile": "pool.log",
"logBaseDirectory": "/opt/miningcore/logs",
"perPoolLogFile": false
},
"banning": {
"manager": "integrated",
"banOnJunkReceive": true,
"banOnInvalidShares": false
},
"api": {
"enabled": true,
"listenAddress": "127.0.0.1",
"port": 4000,
"adminPort": 4001
},

"persistence": {
"postgres": {
"host": "127.0.0.1",
"port": 5432,
"user": "etcpool",
"password": "XXXXXXXXX",
"database": "etcpool"
}
},
"paymentProcessing": {
"enabled": true,
"interval": 600,
"shareRecoveryFile": "recovered-shares.txt"
},
"pools": [{
"id": "ergo",
"enabled": true,
"coin": "ergo",
"address": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"rewardRecipients": [
{
"address": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"percentage": 1
}
],
"blockRefreshInterval": 500,
"clientConnectionTimeout": 600,
"banning": {
"enabled": true,
"time": 600,
"invalidPercent": 50,
"checkThreshold": 50
},
"ports": {
"3032": {
"listenAddress": "0.0.0.0",
"difficulty": 7500,
"name": "CPU Mining",
"varDiff": {
"minDiff": 1000,
"maxDiff": null,
"targetTime": 15,
"retargetTime": 90,
"variancePercent": 30
}
},
"3033": {
"listenAddress": "0.0.0.0",
"difficulty": 25000,
"name": "GPU Mining",
"varDiff": {
"minDiff": 10000,
"maxDiff": null,
"targetTime": 15,
"retargetTime": 90,
"variancePercent": 30
}
},
"3034": {
"listenAddress": "0.0.0.0",
"difficulty": 200000,
"name": "High-End Multi GPU Mining",
"varDiff": {
"minDiff": 200000,
"maxDiff": null,
"targetTime": 15,
"retargetTime": 120,
"variancePercent": 30
}
}
},
"daemons": [
{
"host": "127.0.0.1",
"port": 9053,
"apiKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
},
],
"paymentProcessing": {
"enabled": true,
"minimumPayment": 0.5,
"minimumPaymentToPaymentId": 1.0,
"payoutScheme": "PPLNS",
"payoutSchemeConfig": {
"factor": 2.0
}
}
}]
}

Any help would be appreciated

**Comment by oliverw** [comment]
Could you post your redacted config.json (minus passwords etc)?
