### ISSUE TITLE
Ethereum Connection Error

### ISSUE THREAD

**Issue by konstiantyn** [oliverw/miningcore#1054]
[2021-12-29 08:14:14.2062] [I] [eth] [0HMDO1OVS9IPC] Accepting connection from ::ffff:188.166.161.62:30942 ...
[2021-12-29 08:14:14.2062] [I] [eth] [0HMDO1OVS9IPC] Connection from ::ffff:188.166.161.62:30942 accepted on port 3092
[2021-12-29 08:14:14.2372] [I] [eth] [0HMDO1OVS9IOV] Booting zombie-worker (post-connect silence)
[2021-12-29 08:14:14.2372] [I] [eth] [0HMDO1OVS9IOV] Connection closed
[2021-12-29 08:14:14.2605] [I] [eth] [0HMDO1OVS9IP0] Booting zombie-worker (post-connect silence)
[2021-12-29 08:14:14.2605] [I] [eth] [0HMDO1OVS9IP0] Connection closed
[2021-12-29 08:14:14.2707] [E] [eth] [0HMDO1OVS9IPC] Connection error state: System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Mining.PoolBase.GetNicehashStaticMinDiff(StratumConnection connection, String userAgent, String coinName, String algoName) in /home/pool/Miningcore_test/src/Miningcore/Mining/PoolBase.cs:line 321
   at Miningcore.Blockchain.Ethereum.EthereumPool.OnAuthorizeAsync(StratumConnection connection, Timestamped`1 tsRequest) in /home/pool/Miningcore_test/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs:line 150
   at Miningcore.Blockchain.Ethereum.EthereumPool.OnRequestAsync(StratumConnection client, Timestamped`1 tsRequest, CancellationToken ct) in /home/pool/Miningcore_test/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs:line 364
   at Miningcore.Stratum.StratumServer.OnRequestAsync(StratumConnection connection, JsonRpcRequest request, CancellationToken ct) in /home/pool/Miningcore_test/src/Miningcore/Stratum/StratumServer.cs:line 188
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func`4 onRequestAsync, ReadOnlySequence`1 lineBuffer) in /home/pool/Miningcore_test/src/Miningcore/Stratum/StratumConnection.cs:line 364
   at Miningcore.Stratum.StratumConnection.ProcessReceivePipeAsync(CancellationToken ct, TcpProxyProtocolConfig proxyProtocol, Func`4 onRequestAsync) in /home/pool/Miningcore_test/src/Miningcore/Stratum/StratumConnection.cs:line 286
[2021-12-29 08:14:14.2707] [I] [eth] [0HMDO1OVS9IPC] Connection closed
[2021-12-29 08:14:14.3734] [I] [eth] [0HMDO1OVS80VN] Share accepted: D=1.578
[2021-12-29 08:14:14.4432] [I] [eth] [0HMDO1OVS80VS] Share accepted: D=1.325
[2021-12-29 08:14:14.4712] [I] [eth] [0HMDO1OVS80V7] Share accepted: D=1.746
[2021-12-29 08:14:14.5734] [I] [eth] [0HMDO1OVS80VN] Share accepted: D=1.578

I can't understand this error.

**Comment by oliverw** [comment]
I will have a look after new year.
________________________________
Von: Konstiantyn ***@***.***>
Gesendet: Wednesday, December 29, 2021 9:19:41 AM
An: oliverw/miningcore ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [oliverw/miningcore] Ethereum Connection Error (Issue #1054)


[2021-12-29 08:14:14.2062] [I] [eth] [0HMDO1OVS9IPC] Accepting connection from ::ffff:188.166.161.62:30942 ...
[2021-12-29 08:14:14.2062] [I] [eth] [0HMDO1OVS9IPC] Connection from ::ffff:188.166.161.62:30942 accepted on port 3092
[2021-12-29 08:14:14.2372] [I] [eth] [0HMDO1OVS9IOV] Booting zombie-worker (post-connect silence)
[2021-12-29 08:14:14.2372] [I] [eth] [0HMDO1OVS9IOV] Connection closed
[2021-12-29 08:14:14.2605] [I] [eth] [0HMDO1OVS9IP0] Booting zombie-worker (post-connect silence)
[2021-12-29 08:14:14.2605] [I] [eth] [0HMDO1OVS9IP0] Connection closed
[2021-12-29 08:14:14.2707] [E] [eth] [0HMDO1OVS9IPC] Connection error state: System.NullReferenceException: Object reference not set to an instance of an object.
at Miningcore.Mining.PoolBase.GetNicehashStaticMinDiff(StratumConnection connection, String userAgent, String coinName, String algoName) in /home/pool/Miningcore_test/src/Miningcore/Mining/PoolBase.cs:line 321
at Miningcore.Blockchain.Ethereum.EthereumPool.OnAuthorizeAsync(StratumConnection connection, Timestamped1 tsRequest) in /home/pool/Miningcore_test/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs:line 150 at Miningcore.Blockchain.Ethereum.EthereumPool.OnRequestAsync(StratumConnection client, Timestamped1 tsRequest, CancellationToken ct) in /home/pool/Miningcore_test/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs:line 364
at Miningcore.Stratum.StratumServer.OnRequestAsync(StratumConnection connection, JsonRpcRequest request, CancellationToken ct) in /home/pool/Miningcore_test/src/Miningcore/Stratum/StratumServer.cs:line 188
at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func4 onRequestAsync, ReadOnlySequence1 lineBuffer) in /home/pool/Miningcore_test/src/Miningcore/Stratum/StratumConnection.cs:line 364
at Miningcore.Stratum.StratumConnection.ProcessReceivePipeAsync(CancellationToken ct, TcpProxyProtocolConfig proxyProtocol, Func`4 onRequestAsync) in /home/pool/Miningcore_test/src/Miningcore/Stratum/StratumConnection.cs:line 286
[2021-12-29 08:14:14.2707] [I] [eth] [0HMDO1OVS9IPC] Connection closed
[2021-12-29 08:14:14.3734] [I] [eth] [0HMDO1OVS80VN] Share accepted: D=1.578
[2021-12-29 08:14:14.4432] [I] [eth] [0HMDO1OVS80VS] Share accepted: D=1.325
[2021-12-29 08:14:14.4712] [I] [eth] [0HMDO1OVS80V7] Share accepted: D=1.746
[2021-12-29 08:14:14.5734] [I] [eth] [0HMDO1OVS80VN] Share accepted: D=1.578

I can't understand this error.

**Comment by oliverw** [comment]
Did you try mining on your pool using Nicehash?

**Comment by konstiantyn** [comment]
Yes. I'm using nicehash.

**Comment by oliverw** [comment]
Could you please retest using Release 66?

**Comment by konstiantyn** [comment]
Let me try v66.

**Comment by oliverw** [comment]
> Let me try v66.

Any update?
