### ISSUE TITLE
Enabling admin notifications causes program to crash

### ISSUE THREAD

**Issue by furcalor** [oliverw/miningcore#1059]
If admin notifications are enabled, the software crashes. If admin is disabled there are no errors.
   "notifications": {
        "enabled": true,
        "email": {
            "host": "smtp.gmail.com",
            "port": 587,
            "user": "email@gmail.com",
            "password": "password",
            "fromAddress": "email@gmail.com",
            "fromName": "email@gmail.com"
        },
        "admin": {
            "enabled": true,
            "emailAddress": "email@gmail.com",
            "notifyBlockFound": true
        }
    },

Error:
```
[2022-01-02 23:34:35.2453] [I] [XmlKeyManager] User profile is available. Using '/home/ubuntu/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
[2022-01-02 23:34:35.3877] [E] [Host] BackgroundService failed System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Miningcore.Notifications.NotificationService.ExecuteAsync(CancellationToken ct) in /home/ubuntu/temp/miningcore/src/Miningcore/Notifications/NotificationService.cs:line 156
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)    at Miningcore.Notifications.NotificationService.ExecuteAsync(CancellationToken ct) in /home/ubuntu/temp/miningcore/s                                                                                rc/Miningcore/Notifications/NotificationService.cs:line 156
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[2022-01-02 23:34:35.4012] [F] [Host] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, config                                                                                ure this to Ignore; however the BackgroundService will not be restarted. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Miningcore.Notifications.NotificationService.ExecuteAsync(CancellationToken ct) in /home/ubuntu/temp/miningcore/src/Miningcore/Notifications/NotificationService.cs:line 156
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)    at Miningcore.Notifications.NotificationService.ExecuteAsync(CancellationToken ct) in /home/ubuntu/temp/miningcore/s                                                                                rc/Miningcore/Notifications/NotificationService.cs:line 156
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[2022-01-02 23:34:35.4012] [I] [Lifetime] Application is shutting down...
```

**Comment by oliverw** [comment]
Need more information on this.

**Comment by furcalor** [comment]
What info do you need? More than happy to provide.

**Comment by oliverw** [comment]
Your redacted config file (minus passwords etc).

**Comment by furcalor** [comment]
{
    "logging":{
       "level": "info",
       "enableConsoleLog": true,
       "enableConsoleColors": true,
       "logFile": "debug.log",
       "apiLogFile": "api.log",
       "logBaseDirectory": "/home/ubuntu/temp/miningcore/testlogs",
       "perPoolLogFile": true
    },
    "api": {
        "enabled": true,
        "listenAddress": "0.0.0.0",
         "sslConfig": {
           "enabled": false,
           "sslPath": "/home/ubuntu/ssl/arctic.pfx",
           "sslPassword": ""
        },
        "port": 4001,
        "rateLimiting": {
            "disabled": true,
            "rules": [
                {
                    "Endpoint": "*",
                    "Period": "1s",
                    "Limit": 20
                }
            ],
            "ipWhitelist": [
                ""
            ]
        }
    },
    "banning":{
       "banOnJunkReceive": false,
       "banOnInvalidShares": false
    },
    "notifications":{
       "enabled": true,
       "email":{
          "host": "smtp.gmail.com",
          "port": 587,
          "user": "user",
          "password": "password",
          "fromAddress": "email@gmail.com",
          "fromName": "pool"
       },
       "admin":{
          "enabled": true,
          "emailAddress": "email@gmail.com",
          "notifyBlockFound": true
       }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "postgres",
            "password": "password",
            "database": "miningcore"
        }
    },
    "paymentProcessing":{
       "enabled": false,
       "interval": 600,
       "shareRecoveryFile": "recovered-shares.txt"
    },
    "pools": [
{
      "id": "picacoin",
      "enabled": true,
      "coin": "picacoin",
      "addressType": "BechSegwit",
      "bechPrefix": "bc",
      "address": "bc1uhr4zfvycqcxzk287gtz6cmq3vyht27kv0234f",
      "rewardRecipients": [{
              "address": "bc1uhr4zfvycqcxzk287gtz6cmq3vyht27kv0234f",
              "percentage": 0.01
                }],
      "gbtArgs": [ {"rules": ["segwit"] } ],
      "blockRefreshInterval": 500,
      "jobRebroadcastTimeout": 10,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "3923": {
          "listenAddress": "0.0.0.0",
          "difficulty": 8192,
          "name": "ASIC Mining",
          "varDiff": {
            "minDiff": 1024,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        },
        "13923": {
          "listenAddress": "0.0.0.0",
          "difficulty": 500000,
          "name": "Nicehash/High Diff Mining",
          "varDiff": {
            "minDiff": 500000,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        }
      },
      "daemons": [{
          "host": "127.0.0.1",
          "port": 8772,
          "user": "user1",
          "password": "password"
      }],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.0001,
        "payoutScheme": "SOLO", // PROP PPLNS SOLO supported
        "payoutSchemeConfig": { "factor": 2.0 }
      },
    }

]
}

**Comment by furcalor** [comment]
[config.json-error.txt](https://github.com/oliverw/miningcore/files/7803889/config.json-error.txt)

**Comment by oliverw** [comment]
Hmm, I cannot reproduce the crash.

**Comment by lurchinms** [comment]
https://github.com/lurchinms/kriptokyng_miningcore/commit/74d3409dd2bc69ea5ca786630f60dfbb4e63bd53
