### ISSUE TITLE
Eth Payout Issue

### ISSUE THREAD

**Issue by konstiantyn** [oliverw/miningcore#1141]
[2022-01-27 13:10:14.6165] [I] [PPLNS Payment] Fetching page 0 of shares for pool eth, block 11880690
[2022-01-27 13:10:14.6240] [I] [PPLNS Payment] Balance-calculation for pool eth, block 11880690 completed with accumulated score 0.5 (100%)
[2022-01-27 13:10:14.6240] [I] [PPLNS Payment] Adding 2.05797 ETH to balance of 0xec8b566e2849dbc08e34418bcd9a73a4d3cfa1ac for 1.39 G (1391212238.2371106) shares for block 11880690
[2022-01-27 13:10:14.6352] [I] [PPLNS Payment] Fetching page 0 of discarded shares for pool eth, block 11880690
[2022-01-27 13:10:14.6352] [I] [PPLNS Payment] 695.61 M (695606119.1185553) total discarded shares, block 11880690
[2022-01-27 13:10:14.6352] [I] [PPLNS Payment] 0xec8b566e2849dbc08e34418bcd9a73a4d3cfa1ac = 695.61 M (695606119.1185553) discarded shares, block 11880690
[2022-01-27 13:10:14.6387] [I] [PPLNS Payment] Deleting 1 discarded shares before 2022-01-27T10:29:49.5202970Z
[2022-01-27 13:10:14.6436] [I] [PPLNS Payment] 1.39 G (1391212238.24) shares contributed to a total payout of 2.05797 ETH (100.00% of block reward) to 1 addresses
[2022-01-27 13:10:14.6523] [E] [PayoutManager] [eth] Payment processing failed System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable.
   at Npgsql.NpgsqlTransaction.CheckReady()
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlTransaction.Rollback()
   at Miningcore.Extensions.ConnectionFactoryExtensions.RunTx(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /home/dev/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 56
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /home/dev/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 164
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /home/dev/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 104    at Npgsql.NpgsqlTransaction.CheckReady()
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlTransaction.Rollback()
   at Miningcore.Extensions.ConnectionFactoryExtensions.RunTx(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /home/dev/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 56
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /home/dev/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 164
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /home/dev/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 104

I have just got this error in latest version.

**Comment by BitWizJason** [comment]
The error is somewhat misleading. The SQL failed to execute for some reason and so it tries to rollback the transaction. However, during the transaction rollback it throws and exception because "This NpgsqlTransaction has completed; it is no longer usable."

If you wrap the call to rollback in a try/catch you should be able to determine the true error. I have some changes to help with this that I plan to submit in a PR soon.
