### ISSUE TITLE
vertcoin adding error

### ISSUE THREAD

**Issue by xsiroxcoin** [oliverw/miningcore#1173]
hello when i try to add vertcoin i see this error, how can i fix

[2022-02-23 20:48:41.3924] [E] [Host] BackgroundService failed System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Crypto.Hashing.Algorithms.Verthash.DigestInit(PoolConfig poolConfig) in /home/app/miningcore/src/Miningcore/Crypto/Hashing/Algorithms/Verthash.cs:line 43
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManager.PostChainIdentifyConfigure() in /home/app/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 73
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase1.PostStartInitAsync(CancellationToken ct) in /home/app/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobMa
   at Miningcore.Blockchain.JobManagerBase1.StartAsync(CancellationToken ct) in /home/app/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 110
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in /home/app/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 368
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /home/app/miningcore/src/Miningcore/Mining/PoolBase.cs:line 372
   at Miningcore.Program.<>cDisplayClass17_0.<<RunPool>b0>d.MoveNext() in /home/app/miningcore/src/Miningcore/Program.cs:line 386
--- End of stack trace from previous location ---

**Comment by seperatis** [comment]
Need more info, please share your config file.

**Comment by xsiroxcoin** [comment]
[2022-02-27 12:58:43.5121] [I] [Verthash] Loading verthash data file verthash.dat
[2022-02-27 12:58:43.5121] [E] [vtc1] Verthash initialization failed

i see this error when run pool
