### ISSUE TITLE
I am not sure why this is happening:

### ISSUE THREAD

**Issue by IQTechSolutions** [oliverw/miningcore#1241]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by IQTechSolutions** [comment]
[2022-04-28 14:48:47.5974] [E] [PayoutManager] [eth1] Payment processing failed System.Collections.Generic.KeyNotFoundException: The given key '21616' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.<>c__DisplayClass15_0.<FetchBlocks>b__1(Int64 x) in C:\Users\Administrator\Blockchain\miningcore\src\Miningcore\Blockchain\Ethereum\EthereumPayoutHandler.cs:line 306
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.FetchBlocks(Dictionary`2 blockCache, CancellationToken ct, Int64[] blockHeights) in C:\Users\Administrator\Blockchain\miningcore\src\Miningcore\Blockchain\Ethereum\EthereumPayoutHandler.cs:line 306
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in C:\Users\Administrator\Blockchain\miningcore\src\Miningcore\Blockchain\Ethereum\EthereumPayoutHandler.cs:line 102
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in C:\Users\Administrator\Blockchain\miningcore\src\Miningcore\Payments\PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in C:\Users\Administrator\Blockchain\miningcore\src\Miningcore\Payments\PayoutManager.cs:line 104    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.<>c__DisplayClass15_0.<FetchBlocks>b__1(Int64 x) in C:\Users\Administrator\Blockchain\miningcore\src\Miningcore\Blockchain\Ethereum\EthereumPayoutHandler.cs:line 306
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.FetchBlocks(Dictionary`2 blockCache, CancellationToken ct, Int64[] blockHeights) in C:\Users\Administrator\Blockchain\miningcore\src\Miningcore\Blockchain\Ethereum\EthereumPayoutHandler.cs:line 306
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in C:\Users\Administrator\Blockchain\miningcore\src\Miningcore\Blockchain\Ethereum\EthereumPayoutHandler.cs:line 102
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in C:\Users\Administrator\Blockchain\miningcore\src\Miningcore\Payments\PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in C:\Users\Administrator\Blockchain\miningcore\src\Miningcore\Payments\PayoutManager.cs:line 104

**Comment by IQTechSolutions** [comment]
I have upgraded postgresql, i have uninstalled it and reinstalled it. The only thing I can think of is to delete the database

**Comment by oliverw** [comment]
The database is still there otherwise you would not even get that far. For some reason the handler cannot retrieve block 21616 from geth using `eth_getBlockByNumber`. What happens when you attach to geth from the console and try `eth.getBlock(21616)` ? By the way, is this testnet? The blocknumber is suspicously low.

**Comment by IQTechSolutions** [comment]
<http://www.iqtechsolutions.co.za/images/email/Email-Logo.png> 

	




Hi ,

Thank You very much for the awesomely quick reply. It was on testnet I am setting up a couple of full production pools on all the major coins. It was on testnet. Was testing your pool software and must say I am very impressed with your code. This is really well done thank you for being awesome and writing this and making it available for free and still providing better support than most companies. I am currently syncing on the mainnet and decided to go with your software. I could not find the issue and ended up recreating the database which solved the issue of course. As far as I could tell you can just backup the shares table and then you can recreate the a empty database and just restore the shares. Tried it and it worked perfectly. Thank you once again.


Thank You 
Yours Sincerely, 

Ivan Rossouw 
066 393 0813 / 072 811 7155

	



  <http://www.iqtechsolutions.co.za/images/email/Full-Logo.png> 


IQ Tech Solutions 


Web: 

http://www.iqtechsolutions.co.za 


Email: 

***@***.*** 


Office: 

(021) 006 2221 


Cell: 

0764348180 


Address: 

9 Wentworth Close 

	
Durbanville 

	
Cape Town, 7551 

	


DISCLAIMER: The views and opinions expressed in this message are those of the individual sender of this message and do not necessarily represent the views and opinions of IC Web Designs & Data Development t/a IQ Tech Solutions. Consequently, IQ Tech Solutions does not accept responsibility for such views and opinions and this message should not be read as representing the views and opinions of IQ Tech Solutions without subsequent written confirmation. Each page attached hereto must also be read in conjunction with this disclaimer. 

CONFIDENTIALITY: This e-mail transmission contains confidential information that is the property of the sender and which is legally privileged. The information is intended for the use of the addressee only. If you are not the intended recipient, you are hereby notified that any disclosure, copying or distribution of the contents of this e-mail transmission, or the taking of any action in reliance thereon or pursuant thereto, is strictly prohibited. Should you have received this e-mail in error, please delete it and notify the sender immediately. 

Copyright 2019 IQ Tech Solutions - Powered by ASP.NET
