### ISSUE TITLE
Diagnostics - Application startup exception

### ISSUE THREAD

**Issue by mboyd1** [oliverw/miningcore#1256]
I have been unable to get miningcore to start up, even using the example basic configuration.  It is crashing in the Diagnostics functionality, apparently.  any help is appreciated

> [2022-05-16 18:04:09.3909] [I] [Core] Version 69.0.1.0-master [3e313fda148e00d2aa17d047126df358813da66d]
[2022-05-16 18:04:09.4028] [I] [Core] Runtime .NET 6.0.4 on Linux 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 [X64]
[2022-05-16 18:04:09.4065] [I] [Core] Prometheus Metrics API listening on http://127.0.0.1:4000/metrics
[2022-05-16 18:04:09.4065] [I] [Core] WebSocket Events streaming on ws://127.0.0.1:4000/notifications
[2022-05-16 18:04:09.9825] [I] [XmlKeyManager] User profile is available. Using '/home/miningcore/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
[2022-05-16 18:04:09.9949] [I] [ShareRecorder] Online
[2022-05-16 18:04:10.0185] [I] [PayoutManager] Online
[2022-05-16 18:04:10.0185] [I] [StatsRecorder] Online
[2022-05-16 18:04:10.0747] [I] [Core] 63 coins loaded from '/home/miningcore/git/miningcore/build/coins.json'
[2022-05-16 18:04:10.0857] [I] [btc-1] Starting Pool ...
[2022-05-16 18:04:10.0877] [I] [btc-1] ExtraNonceProvider using 4 bits for instance id, 28 bits for 268435455 values, instance id = 0x8
[2022-05-16 18:04:10.0903] [I] [btc-1] Starting Job Manager ...
[2022-05-16 18:04:10.1321] [I] [Core] API Access to /api/admin restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2022-05-16 18:04:10.1321] [I] [Core] API Access to /metrics restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2022-05-16 18:04:10.1348] [I] [btc-1] All daemons online
[2022-05-16 18:04:10.1414] [F] [Diagnostics] Application startup exception System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Program.<>c.<Main>b__0_9(JsonOptions options) in /home/miningcore/git/miningcore/src/Miningcore/Program.cs:line 181
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Mvc.MvcCoreMvcOptionsSetup.Configure(MvcOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app)
   at Miningcore.Program.<>c__DisplayClass0_0.<Main>b__5(IApplicationBuilder app) in /home/miningcore/git/miningcore/src/Miningcore/Program.cs:line 230
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass17_0.<Configure>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)    at Miningcore.Program.<>c.<Main>b__0_9(JsonOptions options) in /home/miningcore/git/miningcore/src/Miningcore/Program.cs:line 181
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Mvc.MvcCoreMvcOptionsSetup.Configure(MvcOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app)
   at Miningcore.Program.<>c__DisplayClass0_0.<Main>b__5(IApplicationBuilder app) in /home/miningcore/git/miningcore/src/Miningcore/Program.cs:line 230
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass17_0.<Configure>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
[2022-05-16 18:04:10.1511] [I] [Lifetime] Application is shutting down...
System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Program.<>c.<Main>b__0_9(JsonOptions options) in /home/miningcore/git/miningcore/src/Miningcore/Program.cs:line 181
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Mvc.MvcCoreMvcOptionsSetup.Configure(MvcOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app)
   at Miningcore.Program.<>c__DisplayClass0_0.<Main>b__5(IApplicationBuilder app) in /home/miningcore/git/miningcore/src/Miningcore/Program.cs:line 230
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass17_0.<Configure>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Miningcore.Program.Main(String[] args) in /home/miningcore/git/miningcore/src/Miningcore/Program.cs:line 242
Cluster cannot start. Good Bye!

**Comment by mboyd1** [comment]
tried in a Debian 11 docker container and eventually get to the same crash

**Comment by gujingfei** [comment]
Hi, @mboyd1,  I meet the same problem, could you share me your fix or config.json file? Thanks a million.

**Comment by ovladani** [comment]
@mboyd1,  i meet the same issue,  it have been several days, but i still can not fix it. 
is there any error in config.json?
could you help share your fix or config.json... thanks a million..
