### ISSUE TITLE
MC is not EIP27 compatible

### ISSUE THREAD

**Issue by ei8ht187** [oliverw/miningcore#1280]
**Describe the bug**
We mined a block after EIP27 got activated. Payment still processes as normal 63ERG reward:
```
[2022-06-23 07:41:31.8541] [I] [ergo1] [Ergo Payout Handler] Unlocked block 777290 worth 63.0656 ERG
[2022-06-23 07:41:31.8541] [I] [PayoutManager] Processing payments for pool ergo1, block 777290 
[2022-06-23 07:41:31.8615] [I] [ergo1] Adding 0.63066 ERG to balance of 9fS
[2022-06-23 07:41:31.9606] [I] [PPLNS Payment] Fetching page 0 of shares for pool ergo1, block 777290 
[SNIP]
[2022-06-23 07:41:36.3814] [I] [PPLNS Payment] Fetching page 7 of shares for pool ergo1, block 777290 
[2022-06-23 07:41:37.1443] [I] [PPLNS Payment] Balance-calculation for pool ergo1, block 777290 completed with accumulated score 1 (100%) 
[2022-06-23 07:41:40.6231] [I] [PPLNS Payment] Fetching page 0 of discarded shares for pool ergo1, block 777290 
[SNIP]
[2022-06-23 07:41:42.5840] [I] [PPLNS Payment] Fetching page 6 of discarded shares for pool ergo1, block 777290 
[2022-06-23 07:41:44.1037] [I] [ergo1] [Ergo Payout Handler] Paying 62.35399 ERG to 3 addresses 
[2022-06-23 07:41:44.1210] [I] [ergo1] [Ergo Payout Handler] Unlocking wallet 
[2022-06-23 07:41:44.1894] [I] [ergo1] [Ergo Payout Handler] Wallet unlocked 
[2022-06-23 07:41:44.2032] [I] [ergo1] [Ergo Payout Handler] Current wallet balance is [SNIP]
[2022-06-23 07:41:44.2032] [I] [ergo1] Validating addresses ... 
[2022-06-23 07:41:44.2491] [I] [ergo1] [Ergo Payout Handler] Payment transaction id: e8c7
[2022-06-23 07:41:44.2807] [I] [ergo1] [Ergo Payout Handler] Resetting balance of 9iH
[2022-06-23 07:41:44.3356] [I] [ergo1] [Ergo Payout Handler] Resetting balance of 9hR
[2022-06-23 07:41:44.3791] [I] [ergo1] [Ergo Payout Handler] Resetting balance of 9gs
[2022-06-23 07:41:44.4251] [I] [ergo1] [Ergo Payout Handler] Locking wallet 
[2022-06-23 07:41:44.4383] [I] [ergo1] [Ergo Payout Handler] Wallet locked 

```

**To Reproduce**
Mine a block, wait for payout

**Expected behavior**
EIP27 adjustments have to be included for payout

**Screenshots**

**Additional context**
Our Payout ERGO node is running Ergo 4.0.31 with the following configuration: 
```
ergo {
  node {
    mining = true
    useExternalMiner = true
  }
  voting {
    8 = 1000
  }
  chain {
    reemission {
      checkReemissionRules = true
    }
  }
  wallet {
    checkEIP27 = true
  }
}

scorex {
 restApi {
    # Hex-encoded Blake2b256 hash of an API key. 
    # Should be 64-chars long Base16 string.
    # below is the hash of the string 'hello'
    # replace with your actual hash 
   apiKeyHash = "[SNIP]"
  }
}
```

and our fullnodes for stratum uses the following configuration, also with v4.0.31:
```
ergo {
  node {
    mining = true
    useExternalMiner = true
    miningPubKeyHex = [SNIP]
  }
  voting {
    8 = 1000
  }
  chain {
    reemission {
      checkReemissionRules = true
    }
  }
  wallet {
    checkEIP27 = true
  }
}

scorex {
 restApi {
    # Hex-encoded Blake2b256 hash of an API key. 
    # Should be 64-chars long Base16 string.
    # below is the hash of the string 'hello'
    # replace with your actual hash 
   apiKeyHash = "[SNIP]"
  }
}
```

**Comment by oliverw** [comment]
Can't deduce the problem from the log output.

**Comment by ei8ht187** [comment]
With EIP27 the payout scheme changed. 
Blockreward is still 63ERG, but 12ERG are taken from the blockchain itself to a reemission smart contract, so only 51ERG get paid into the pool wallet. The normal emission deduction of 3ERG every 3Month remains, next is in a few days, meaning only 48ERG reward per block.
This continues as long as the blockerward is bigger than 15ERG. With with 15, the reward is 15 ERG. Below 15ERG blockreward, you get additional 3ERG from the reemission smart contract.

See this Transaction:
https://explorer.ergoplatform.com/en/transactions/e8c7793baabdacec253c57289f4eb4f6ca413ac2c65748d51c5fa1d58157ccad

In particular the 12ERG sent to 6Kxused. This is the reemission smartcontract. The rest of the blockreward (including TX fees) is sent to our poolwallet, visible when you open the "show more" part on the explorer

**Comment by oliverw** [comment]
At least on testnet this was handled transparently by the node. Investigating.

**Comment by oliverw** [comment]
Can you guys give the latest `dev` branch a shot?

**Comment by btclinux** [comment]
> Can you guys give the latest `dev` branch a shot?

[2022-06-24 11:08:32.5725] [E] [ergo] Daemon reports: Could not deserialize the response body stream as Miningcore.Blockchain.Ergo.NodeInfo.

Status: 200
Response: 
 
[2022-06-24 11:08:32.5779] [E] [Core] Cluster cannot start. Good Bye!

**Comment by oliverw** [comment]
> > Can you guys give the latest `dev` branch a shot?
> 
> [2022-06-24 11:08:32.5725] [E] [ergo] Daemon reports: Could not deserialize the response body stream as Miningcore.Blockchain.Ergo.NodeInfo.
> 
> Status: 200 Response:
> 
> [2022-06-24 11:08:32.5779] [E] [Core] Cluster cannot start. Good Bye!

Weird.

**Comment by oliverw** [comment]
Pushed a new commit.

**Comment by ei8ht187** [comment]
Stratum itself is starting fine, Masternode gives 403 error: 
```
[2022-06-24 20:37:58.5075] [E] [ergo1] HTTP Response: 



Miningcore.Blockchain.Ergo.ApiException`1[Miningcore.Blockchain.Ergo.ApiError]: Error

Status: 403
Response: 

   at Miningcore.Blockchain.Ergo.ErgoClient.WalletAddressesAsync(CancellationToken cancellationToken) in /app/src/Miningcore/Blockchain/Ergo/RPC/ErgoClient.cs:line 4986
   at Miningcore.Blockchain.Ergo.ErgoJobManager.PostStartInitAsync(CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoJobManager.cs:line 377
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /app/src/Miningcore/Blockchain/JobManagerBase.cs:line 112
   at Miningcore.Blockchain.Ergo.ErgoPool.SetupJobManager(CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPool.cs:line 289
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /app/src/Miningcore/Mining/PoolBase.cs:line 393 HTTP Response: 
```
Both are running on the same node, only difference is shareRealy/shareRelays config and that stratum node is also ERGO node on our internal testsetup.

**Comment by oliverw** [comment]
Latest commit should fix that.

**Comment by ei8ht187** [comment]
Ok, everything is starting now, just payments are failing: 
```
2022-06-26 18:32:56.9446] [I] [PayoutManager] Processing payments for pool ergo1 
[2022-06-26 18:32:56.9644] [E] [PayoutManager] [ergo1] Payment processing failed System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 211
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 211
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104
[2022-06-26 18:33:06.5534] [I] [ergo1] External [DEV MASTERNODE1] share accepted: D=0.9
```

**Comment by oliverw** [comment]
Can you run a debug build please and post the crash log?

**Comment by ei8ht187** [comment]
> Can you run a debug build please and post the crash log?
Sure. Sadly, round the payment processing part is nothing more visible than above:
```
[2022-06-26 18:53:12.6960] [I] [ergo1] External [DEV MASTERNODE1] share accepted: D=1 
[2022-06-26 18:53:21.9508] [D] [DefaultHttpClientFactory] HttpMessageHandler expired after 120000ms for client '' 
[2022-06-26 18:53:31.9540] [D] [DefaultHttpClientFactory] Starting HttpMessageHandler cleanup cycle with 1 items 
[2022-06-26 18:53:31.9577] [D] [DefaultHttpClientFactory] Ending HttpMessageHandler cleanup cycle after 0.5071ms - processed: 0 items - remaining: 1 items 
[2022-06-26 18:53:37.1477] [I] [StatsRecorder] [ergo1] Updating Statistics for pool 
[2022-06-26 18:53:37.1657] [I] [StatsRecorder] [ergo1] Worker 3WwnDhmwo24p3oMWP2C8iH2ahg3YJH1Bm8vZ7n6bUqUVvvvHs1h6: 29.64 MH/s, 0.007 shares/sec 
[2022-06-26 18:53:37.1657] [I] [StatsRecorder] [ergo1] Miner 3WwnDhmwo24p3oMWP2C8iH2ahg3YJH1Bm8vZ7n6bUqUVvvvHs1h6: 29.64 MH/s 
[2022-06-26 18:53:41.9585] [D] [DefaultHttpClientFactory] Starting HttpMessageHandler cleanup cycle with 1 items 
[2022-06-26 18:53:41.9585] [D] [DefaultHttpClientFactory] Ending HttpMessageHandler cleanup cycle after 0.0055ms - processed: 0 items - remaining: 1 items 
[2022-06-26 18:53:51.9600] [D] [DefaultHttpClientFactory] Starting HttpMessageHandler cleanup cycle with 1 items 
[2022-06-26 18:53:51.9600] [D] [DefaultHttpClientFactory] Ending HttpMessageHandler cleanup cycle after 0.0015ms - processed: 0 items - remaining: 1 items 
[2022-06-26 18:53:52.2807] [D] [Sockets] Connection id "0HMINKJESRFM2" received FIN. 
[2022-06-26 18:53:52.2829] [D] [Connections] Connection id "0HMINKJESRFM2" disconnecting. 
[2022-06-26 18:53:52.2829] [D] [Sockets] Connection id "0HMINKJESRFM2" sending FIN because: "The client closed the connection." 
[2022-06-26 18:53:52.2829] [D] [Sockets] Connection id "0HMINKJESRFM3" received FIN. 
[2022-06-26 18:53:52.2858] [D] [Connections] Connection id "0HMINKJESRFM3" disconnecting. 
[2022-06-26 18:53:52.2858] [D] [Connections] Connection id "0HMINKJESRFM2" stopped. 
[2022-06-26 18:53:52.2858] [D] [Connections] Connection id "0HMINKJESRFM3" stopped. 
[2022-06-26 18:53:52.2920] [D] [Sockets] Connection id "0HMINKJESRFM3" sending FIN because: "The Socket transport's send loop completed gracefully." 
[2022-06-26 18:54:01.9593] [D] [DefaultHttpClientFactory] Starting HttpMessageHandler cleanup cycle with 1 items 
[2022-06-26 18:54:01.9593] [D] [DefaultHttpClientFactory] Ending HttpMessageHandler cleanup cycle after 0.0014ms - processed: 0 items - remaining: 1 items 
[2022-06-26 18:54:02.1517] [I] [PayoutManager] Processing payments for pool ergo1 
[2022-06-26 18:54:02.1739] [E] [PayoutManager] [ergo1] Payment processing failed System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 211
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 211
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104
[2022-06-26 18:54:11.9583] [D] [DefaultHttpClientFactory] Starting HttpMessageHandler cleanup cycle with 1 items 
[2022-06-26 18:54:11.9583] [D] [DefaultHttpClientFactory] Ending HttpMessageHandler cleanup cycle after 0.0017ms - processed: 0 items - remaining: 1 items 
[2022-06-26 18:54:21.9589] [D] [DefaultHttpClientFactory] Starting HttpMessageHandler cleanup cycle with 1 items 
[2022-06-26 18:54:21.9589] [D] [DefaultHttpClientFactory] Ending HttpMessageHandler cleanup cycle after 0.0036ms - processed: 0 items - remaining: 1 items 
[2022-06-26 18:54:24.9220] [I] [ergo1] External [DEV MASTERNODE1] share accepted: D=1
```

**Comment by oliverw** [comment]
Could you retry with latest commit. Not necessary to run a debug build this time.

**Comment by ei8ht187** [comment]
> Could you retry with latest commit. Not necessary to run a debug build this time.

```
[2022-06-27 21:07:49.6316] [I] [PayoutManager] Processing payments for pool ergo1 
[2022-06-27 21:07:49.6496] [I] [ergo1] **1 9728accdec7c1e757709406b4b38e7104f6afbf621d215ebac1f5b39ed0b6197 
[2022-06-27 21:07:49.6538] [I] [ergo1] **2  
[2022-06-27 21:07:49.6538] [E] [PayoutManager] [ergo1] Payment processing failed System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104
[2022-06-27 21:08:11.4178] [I] [RelayReceiver] Receive timeout of 60 seconds exceeded. Re-connecting to tcp://10.200.139.253:6000 ... 
[2022-06-27 21:08:22.7681] [I] [ergo1] Detected new block 257535 [POLL] 
[2022-06-27 21:08:24.6354] [I] [StatsRecorder] [ergo1] Updating Statistics for pool 
[2022-06-27 21:08:24.8343] [I] [StatsRecorder] [ergo1] Worker 3WwnDhmwo24p3oMWP2C8iH2ahg3YJH1Bm8vZ7n6bUqUVvvvHs1h6: 97.71 MH/s, 0.026 shares/sec 
[2022-06-27 21:08:24.8343] [I] [StatsRecorder] [ergo1] Miner 3WwnDhmwo24p3oMWP2C8iH2ahg3YJH1Bm8vZ7n6bUqUVvvvHs1h6: 97.71 MH/s 
[2022-06-27 21:08:58.8042] [I] [ergo1] Detected new block 257536 [POLL] 
[2022-06-27 21:09:11.4584] [I] [RelayReceiver] Receive timeout of 60 seconds exceeded. Re-connecting to tcp://10.200.139.253:6000 ... 
[2022-06-27 21:09:20.9801] [I] [ergo1] Detected new block 257537 [POLL] 
[2022-06-27 21:09:29.6311] [I] [PayoutManager] Processing payments for pool ergo1 
[2022-06-27 21:09:29.6492] [I] [ergo1] **1 9728accdec7c1e757709406b4b38e7104f6afbf621d215ebac1f5b39ed0b6197 
[2022-06-27 21:09:29.6531] [I] [ergo1] **2  
[2022-06-27 21:09:29.6537] [E] [PayoutManager] [ergo1] Payment processing failed System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104
[2022-06-27 21:10:11.5056] [I] [RelayReceiver] Receive timeout of 60 seconds exceeded. Re-connecting to tcp://10.200.139.253:6000 ... 
[2022-06-27 21:10:16.4288] [I] [ergo1] Detected new block 257538 [POLL] 

```
all in Testnet ofc.

**Comment by oliverw** [comment]
Latest commit should work.

**Comment by oliverw** [comment]
> Output repeats, even after 24h (720 confirmations):
> 
> ```
> [2022-06-28 21:16:09.6336] [I] [PayoutManager] Processing payments for pool ergo1 
> [2022-06-28 21:16:09.6508] [I] [ergo1] **1 9728accdec7c1e757709406b4b38e7104f6afbf621d215ebac1f5b39ed0b6197 
> [2022-06-28 21:16:09.6542] [I] [ergo1] **2  
> [2022-06-28 21:16:09.6542] [E] [PayoutManager] [ergo1] Payment processing failed System.NullReferenceException: Object reference not set to an instance of an object.
>    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
>    at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
>    at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
>    at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
>    at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104
> [2022-06-28 21:16:19.5497] [I] [RelayReceiver] Receive timeout of 60 seconds exceeded. Re-connecting to tcp://10.XXX.XXX.XXX:6000 ... 
> [2022-06-28 21:16:24.6384] [I] [StatsRecorder] [ergo1] Updating Statistics for pool 
> [2022-06-28 21:16:24.6384] [I] [StatsRecorder] [ergo1] Reset performance stats for pool 
> [2022-06-28 21:17:19.5944] [I] [RelayReceiver] Receive timeout of 60 seconds exceeded. Re-connecting to tcp://10.200.139.253:6000 ... 
> [2022-06-28 21:17:49.6320] [I] [PayoutManager] Processing payments for pool ergo1 
> [2022-06-28 21:17:49.6529] [I] [ergo1] **1 9728accdec7c1e757709406b4b38e7104f6afbf621d215ebac1f5b39ed0b6197 
> [2022-06-28 21:17:49.6560] [I] [ergo1] **2  
> [2022-06-28 21:17:49.6560] [E] [PayoutManager] [ergo1] Payment processing failed System.NullReferenceException: Object reference not set to an instance of an object.
>    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
>    at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
>    at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
>    at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
>    at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104
> [2022-06-28 21:18:19.6336] [I] [RelayReceiver] Receive timeout of 60 seconds exceeded. Re-connecting to tcp://10.XXX.XXX.XXX:6000 ... 
> ```

Got a chance to test the latest version?

**Comment by ei8ht187** [comment]
> > Output repeats, even after 24h (720 confirmations):
> > ```
> > [2022-06-28 21:16:09.6336] [I] [PayoutManager] Processing payments for pool ergo1 
> > [2022-06-28 21:16:09.6508] [I] [ergo1] **1 9728accdec7c1e757709406b4b38e7104f6afbf621d215ebac1f5b39ed0b6197 
> > [2022-06-28 21:16:09.6542] [I] [ergo1] **2  
> > [2022-06-28 21:16:09.6542] [E] [PayoutManager] [ergo1] Payment processing failed System.NullReferenceException: Object reference not set to an instance of an object.
> >    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
> >    at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
> >    at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
> >    at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
> >    at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104
> > [2022-06-28 21:16:19.5497] [I] [RelayReceiver] Receive timeout of 60 seconds exceeded. Re-connecting to tcp://10.XXX.XXX.XXX:6000 ... 
> > [2022-06-28 21:16:24.6384] [I] [StatsRecorder] [ergo1] Updating Statistics for pool 
> > [2022-06-28 21:16:24.6384] [I] [StatsRecorder] [ergo1] Reset performance stats for pool 
> > [2022-06-28 21:17:19.5944] [I] [RelayReceiver] Receive timeout of 60 seconds exceeded. Re-connecting to tcp://10.200.139.253:6000 ... 
> > [2022-06-28 21:17:49.6320] [I] [PayoutManager] Processing payments for pool ergo1 
> > [2022-06-28 21:17:49.6529] [I] [ergo1] **1 9728accdec7c1e757709406b4b38e7104f6afbf621d215ebac1f5b39ed0b6197 
> > [2022-06-28 21:17:49.6560] [I] [ergo1] **2  
> > [2022-06-28 21:17:49.6560] [E] [PayoutManager] [ergo1] Payment processing failed System.NullReferenceException: Object reference not set to an instance of an object.
> >    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
> >    at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
> >    at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104    at Miningcore.Blockchain.Ergo.ErgoPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /app/src/Miningcore/Blockchain/Ergo/ErgoPayoutHandler.cs:line 215
> >    at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 156
> >    at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /app/src/Miningcore/Payments/PayoutManager.cs:line 104
> > [2022-06-28 21:18:19.6336] [I] [RelayReceiver] Receive timeout of 60 seconds exceeded. Re-connecting to tcp://10.XXX.XXX.XXX:6000 ... 
> > ```
> 
> Got a chance to test the latest version?

Hello, 
yes in the meantime, even on mainnet. ERGO decided to reboot the testnet and I was again unable to sync with it. 
I can confirm that the payout is now working correctly. 

Thanks a lot for your help

**Comment by kr1z1s** [comment]
Hi
Payouts not fixed

I use llatest DEV branch. Block mined correctly, but payouts cause an error from coin daemon

> [2022-07-04 06:27:32.9850] [E] [ergopool] [Ergo Payout Handler] Payment transaction failed: Bad request List(PaymentRequest(9hWEVADgmuAbuy2XsteCVDrxF4KqEBy6wWM6C8Zf9fVxtzXuKnB,5437300000,List(),Map()), PaymentRequest(9fo4ZaL9yZs8JPKUsghKeHJZuxi4wJ1TNMgnotDHaAJZ3byjhSc,34771700000,List(),Map()), PaymentRequest(9ee1UaZQQrcDKBqNxkC3D4yhr7bkxpwNaq3hxvvqoVNPWs7kWMA,8027500000,List(),Map()), PaymentRequest(9hn7R58gpm22CnEXKEFimKYKuaFhMhWS3yGcyh7jAxq68AvhUcF,152200000,List(),Map()), PaymentRequest(9eg8igGGFjxe8vDRGMvV6mWu1bsZKCiCSfnSzjjX8hbFx9NBp7t,1055300000,List(),Map()), PaymentRequest(9fDADUvGBPnj4NEkdiYvqGTkRBG4GJxBh5HFHsMth4i4PEFqNrS,506300000,List(),Map()), PaymentRequest(9h6ZAzVtRxAPC6XCVn9r8B3ERoJCQyya4wS6WYrMjB6uyrbDZsV,721600000,List(),Map()), PaymentRequest(2iHkR7CWvD1R4j1yZg5bkeDRQavjAaVPeTDFGGLZduHyfWMuYpmhHocX8GJoaieTx78FntzJbCBVL6rf96ocJoZdmWBL2fci7NqWgAirppPQmZ7fN9V6z13Ay6brPriBKYqLp1bT2Fk4FkFLCfdPpe,1000000,List(),Map())). Transaction should conform EIP-27 rules

**Comment by oliverw** [comment]
The last address looks suspicous.

**Comment by kr1z1s** [comment]
> The last address looks suspicous.

Yes. But where did it come from? The pool has been working for a long time. How can I fix this problem?

**Comment by oliverw** [comment]
> > The last address looks suspicous.
> 
> Yes. But where did it come from? The pool has been working for a long time. How can I fix this problem?

Regarding the latter. Please note the balance value for later (until a miner complains about a missing payout with a matching balance). Then open a database connection and do this:

`update balances set amount = 0 where address = '2iHkR7CWvD1R4j1yZg5bkeDRQavjAaVPeTDFGGLZduHyfWMuYpmhHocX8GJoaieTx78FntzJbCBVL6rf96ocJoZdmWBL2fci7NqWgAirppPQmZ7fN9V6z13Ay6brPriBKYqLp1bT2Fk4FkFLCfdPpe';`

**Comment by kr1z1s** [comment]
> > > The last address looks suspicous.
> > 
> > 
> > Yes. But where did it come from? The pool has been working for a long time. How can I fix this problem?
> 
> Regarding the latter. Please note the balance value for later (until a miner complains about a missing payout with a matching balance). Then open a database connection and do this:
> 
> ```sql
> update balances set amount = 0 where address = '2iHkR7CWvD1R4j1yZg5bkeDRQavjAaVPeTDFGGLZduHyfWMuYpmhHocX8GJoaieTx78FntzJbCBVL6rf96ocJoZdmWBL2fci7NqWgAirppPQmZ7fN9V6z13Ay6brPriBKYqLp1bT2Fk4FkFLCfdPpe';
> ```
> 
> For the future do not comment on closed issues but open a new one or a discussion thread.

Ok
https://github.com/oliverw/miningcore/issues/1290#issuecomment-1174080779
