### ISSUE TITLE
eth payout issue

### ISSUE THREAD

**Issue by 0xIbrahim-t** [oliverw/miningcore#1363]
**Describe the bug**
eth payout problem 

Payment processing failed System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable.
   at Npgsql.NpgsqlTransaction.CheckReady()
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlTransaction.Rollback()
   at Miningcore.Extensions.ConnectionFactoryExtensions.RunTx(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /home/stilleto45/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 56
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 164
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 104    at Npgsql.NpgsqlTransaction.CheckReady()
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlTransaction.Rollback()
   at Miningcore.Extensions.ConnectionFactoryExtensions.RunTx(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /home/stilleto45/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 56
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig config, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 164
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 104

**To Reproduce**

just used normal method to reproduce in a private network.

config file:

{
    "$schema": "https://raw.githubusercontent.com/oliverw/miningcore/master/src/Miningcore/config.schema.json",
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "apiLogFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "Integrated",
        "banOnJunkReceive": false,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "pool support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "testpass",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 100,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "api": {
        "enabled": true,
        "listenAddress": "*",
        "port": 4000,
        "metricsIpWhitelist": [],
        "rateLimiting": {
            "disabled": true,
            "rules": [
                {
                    "Endpoint": "*",
                    "Period": "1s",
                    "Limit": 5
                }
            ],
            "ipWhitelist": [
                ""
            ]
        }
    },
    "clusterName": "eu1",
    "pools": [
      {
        "id": "mypool1",
        "enabled": true,
        "coin": "erachain",
        "address": "0x9ab1db1130ae931b35fe7256aa1afc145ee98531",
        "rewardRecipients": [
          {
            "type": "op",
            "address": "0x9ab1db1130ae931b35fe7256aa1afc145ee98531",
            "percentage": 12.0
          }
        ],
        "blockRefreshInterval": 120,
        "clientConnectionTimeout": 60000,
        "banning": {
          "enabled": true,
          "time": 600,
          "invalidPercent": 50,
          "checkThreshold": 50
        },
        "ports": {
          "4073": {
            "name": "GPU-SMALL",
            "listenAddress": "*",
            "difficulty": 0.1,
            "varDiff": {
              "minDiff": 0.1,
              "maxDiff": null,
              "targetTime": 15,
              "retargetTime": 90,
              "variancePercent": 30
            }
          }
        },
        "chainTypeOverride": "Ethereum",
        "dagDir": "./data",
        "daemons": [
          {
            "host": "127.0.0.1",
            "port": 8000,
            "user": "",
            "password": "",
	    "portWs": 8546
          }
        ],
        "paymentProcessing": {
            "enabled": true,
            "minimumPayment": 1,
            "payoutScheme": "PPLNS
            "payoutSchemeConfig": {
                "factor": 0.5
            },
            "gas": 21000,
            "maxFeePerGas": 50000000000,
            "keepUncles": false,
            "keepTransactionFees": false
        }
      }
    ]
}

**Comment by ei8ht187** [comment]
Most likely the same old problem: two entries for the same block in the database. See #1103 for further information or just search in Issues and Discussion

**Comment by 0xIbrahim-t** [comment]
> Most likely the same old problem: two entries for the same block in the database. See #1103 for further information or just search in Issues and Discussion.
> 
> If not, maybe the database timeout is a problem, see #1309

It seems like no one have solved this 

I have already saw all the issues regarding this and still can't resolve it. Can you help me with it ?

**Comment by 05sonicblue** [comment]
I'm also running into this issue with my ETHO pool. Occasionally this happens. I added in some logging statements to validate when it was actually happening and it is indeed on the save of the first record in the loop. In my case, it always seems to be on an uncle block and I verified in blocks table that there isn't a duplicate for that block. 

[2022-08-23 15:26:03.9831] [I] [etho1] [Ethereum Payout Handler] Fetching 1 uncles for block 9882926
[2022-08-23 15:26:03.9860] [I] [etho1] [Ethereum Payout Handler] Fetched 1 uncles for block 9882926
[2022-08-23 15:26:03.9860] [I] [etho1] [Ethereum Payout Handler] Unlocked uncle for block 9882926 at height 9882925 worth 0.2625 ETHO
[2022-08-23 15:26:03.9932] [I] [PayoutManager] Processing payments for pool etho1, block 9880630
[2022-08-23 15:26:04.0098] [I] [PayoutManager] Block Reward: 0.2597375
[2022-08-23 15:26:04.0098] [I] [PayoutManager] Update Balances
[2022-08-23 15:26:04.0500] [I] [PPLNS Payment] Fetching page 0 of shares for pool etho1, block 9880630
[2022-08-23 15:26:04.0900] [I] [PPLNS Payment] Balance-calculation for pool etho1, block 9880630 completed with accumulated score 0.5 (100%)
[2022-08-23 15:26:04.0929] [I] [PPLNS Payment] Crediting 0x1a2a13a009e8953b3c7a652a2a904711353ee998 with 0.25974 ETHO for 30.51G (30509209874.096256) shares for block 9880630
[2022-08-23 15:26:04.1459] [I] [PPLNS Payment] Fetching page 0 of discarded shares for pool etho1, block 9880630
[2022-08-23 15:26:04.1550] [I] [PPLNS Payment] 14.19G (14193529232.189144) total discarded shares, block 9880630
[2022-08-23 15:26:04.1579] [I] [PPLNS Payment] 0x1a2a13a009e8953b3c7a652a2a904711353ee998 = 14.19G (14193529232.189144) discarded shares, block 9880630
[2022-08-23 15:26:04.1579] [I] [PPLNS Payment] Deleting 30 discarded shares before 2022-08-23T07:03:26.9358330Z
[2022-08-23 15:26:04.1837] [I] [PPLNS Payment] 30.51G (30509209874.10) shares contributed to a total payout of 0.25974 ETHO (100.00% of block reward) to 1 addresses
[2022-08-23 15:26:04.1852] [I] [PayoutManager] Update Blocks
[2022-08-23 15:26:04.1958] [I] [BlockRepository] Update Block Query: UPDATE blocks SET blockheight = @blockheight, status = @status, type = @type,
            reward = @reward, effort = @effort, confirmationprogress = @confirmationprogress, hash = @hash WHERE id = @id
[2022-08-23 15:26:04.2034] [I] [PayoutManager] Balances and Blocks Update Logic Complete. Pending TX Save.
[2022-08-23 15:26:04.2188] [E] [PayoutManager] [etho1] Payment processing failed System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable.
   at Npgsql.NpgsqlTransaction.CheckReady()
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlTransaction.Rollback()
   at Miningcore.Extensions.ConnectionFactoryExtensions.RunTx(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /home/michaeldlesk/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 56
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig poolConfig, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /home/michaeldlesk/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 164
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /home/michaeldlesk/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 104    at Npgsql.NpgsqlTransaction.CheckReady()
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlTransaction.Rollback()
   at Miningcore.Extensions.ConnectionFactoryExtensions.RunTx(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /home/michaeldlesk/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 56
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig poolConfig, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /home/michaeldlesk/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 164
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /home/michaeldlesk/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 104

Verified that the block is not duplicated either:
![image](https://user-images.githubusercontent.com/1271856/186200287-9f2c05bd-d20a-458e-aa9f-4e0c38eaa269.png)

**Comment by 0xIbrahim-t** [comment]
there was a duplicate block above and i solved it using removing the duplicate blocks. but i got another problem after that 
@oliverw @ei8ht187 

[2022-08-24 16:03:11.1315] [I] [mypool1] [Ethereum Payout Handler] Sending 144.335 ERA to 0xcdf70c10801544f25a6a758e7231a16e58e155a7
[2022-08-24 16:03:11.1607] [E] [mypool1] System.Exception: eth_sendTransaction returned error: invalid sender code -32000
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(Balance balance, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 411
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(IMiningPool pool, Balance[] balances, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 263 System.Exception: eth_sendTransaction returned error: invalid sender code -32000
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(Balance balance, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 411
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(IMiningPool pool, Balance[] balances, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 263    at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(Balance balance, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 411
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(IMiningPool pool, Balance[] balances, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 263

**Comment by 05sonicblue** [comment]
@0xIbrahim-t Are you using ETH or a different chain? I was having that same problem with ETHO, and all I had to do was to make the MaxPriorityFeePerGas and MaxFeePerGas properties a nullable 64-bit integer instead of a regular 64-bit integer in the /Blockchain/Ethereum/DaemonRequests/SendTransactionRequest.cs file

`
    /// <summary>
    /// Maximum fee per gas the sender is willing to pay to miners in wei.
    /// </summary>
    [JsonConverter(typeof(HexToIntegralTypeJsonConverter<ulong>))]
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
    public ulong? MaxPriorityFeePerGas { get; set; }

    /// <summary>
    /// The maximum total fee per gas the sender is willing to pay(includes the network / base fee and miner / priority fee) in wei
    /// </summary>
    [JsonConverter(typeof(HexToIntegralTypeJsonConverter<ulong>))]
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
    public ulong? MaxFeePerGas { get; set; }
`

**Comment by 0xIbrahim-t** [comment]
@05sonicblue hi, i used a ethereum private chain

**Comment by 0xIbrahim-t** [comment]
@05sonicblue let me give it a try

**Comment by 0xIbrahim-t** [comment]
@05sonicblue hi,

i tried your method but still getting the same error

System.Exception: eth_sendTransaction returned error: invalid sender code -32000
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(Balance balance, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 411
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(IMiningPool pool, Balance[] balances, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 263 System.Exception: eth_sendTransaction returned error: invalid sender code -32000
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(Balance balance, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 411
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(IMiningPool pool, Balance[] balances, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 263    at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(Balance balance, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 411
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(IMiningPool pool, Balance[] balances, CancellationToken ct) in /home/stilleto45/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 263

**Comment by 0xIbrahim-t** [comment]
@oliverw but the issue still haven't resolved?

**Comment by oliverw** [comment]
> @oliverw but the issue still haven't resolved?

Sorry I don't have the resources to spent time on a dead chain.

**Comment by 0xIbrahim-t** [comment]
@oliverw hi sir, is there anybody who can solve for a some amount payment ?

**Comment by blackmennewstyle** [comment]
I am facing the same issue #1583 when trying to implement `ETC`, as first i thought it was because of `block`type issue but apparently it is related to `Npgsql`, the only reference i found about that bug is a 2 years old one: https://github.com/npgsql/npgsql/issues/3384 but it seems to have fixed since then apparently.
