### ISSUE TITLE
Ghostrider doesn't work

### ISSUE THREAD

**Issue by lurchinms** [oliverw/miningcore#1434]
On Ubuntu 20.04

**Comment by lurchinms** [comment]
"jagoancoin": {
        "name": "Jagoancoin",
        "canonicalName": "Jagoancoin",
        "symbol": "JGC",
        "family": "bitcoin",
        "website": "https://jagoancoin.org/",
        "market": "",
        "twitter": "https://twitter.com/jagoanpilot",
        "telegram": "https://t.me/jagoancoin",
        "discord": "https://discord.gg/a3brezx9vD",
        "coinbaseHasher": {
            "hash": "sha256d"
        },
        "headerHasher": {
            "hash": "ghostrider"
        },
        "blockHasher": {
            "hash": "reverse",
            "args": [ { "hash": "sha256d" } ]
        },
        "hasFounderFee": true,
        "hasMasterNodes": true,
        "shareMultiplier": 65536,
        "explorerBlockLink": "https://explorer.jagoancoin.org/block/$hash$",
        "explorerTxLink": "https://explorer.jagoancoin.org/tx/{0}",
        "explorerAccountLink": "https://explorer.jagoancoin.org/address/{0}"
    },

core.log:
[2022-09-27 21:25:34.4650] [E] [jgc] [0HML0V2EA8VTC] Connection error: System.DllNotFoundException: Unable to load shared library 'libcryptonight' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibcryptonight: cannot open shared object file: No such file or directory
   at Miningcore.Native.Cryptonight.alloc_context()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.LazyHelper.ThrowException()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Miningcore.Native.Cryptonight.Context.get_Handle() in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Native/Cryptonight.cs:line 142
   at Miningcore.Native.Cryptonight.CryptonightHash(ReadOnlySpan`1 data, Span`1 result, Algorithm algo, UInt64 height) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Native/Cryptonight.cs:line 192
   at Miningcore.Crypto.Hashing.Algorithms.Ghostrider.Digest(ReadOnlySpan`1 data, Span`1 result, Object[] extra) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Crypto/Hashing/Algorithms/Ghostrider.cs:line 11
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.ProcessShareInternal(StratumConnection worker, String extraNonce2, UInt32 nTime, UInt32 nonce, Nullable`1 versionBits) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 322
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.ProcessShare(StratumConnection worker, String extraNonce2, String nTime, String nonce, String versionBits) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 675
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManager.SubmitShareAsync(StratumConnection worker, Object submission, CancellationToken ct) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 241
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnSubmitAsync(StratumConnection connection, Timestamped`1 tsRequest, CancellationToken ct) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 184
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnRequestAsync(StratumConnection connection, Timestamped`1 tsRequest, CancellationToken ct) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 423
   at Miningcore.Stratum.StratumServer.OnRequestAsync(StratumConnection connection, JsonRpcRequest request, CancellationToken ct) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Stratum/StratumServer.cs:line 200
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func`4 onRequestAsync, ReadOnlySequence`1 lineBuffer) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Stratum/StratumConnection.cs:line 376
   at Miningcore.Stratum.StratumConnection.ProcessReceivePipeAsync(CancellationToken ct, TcpProxyProtocolConfig proxyProtocol, Func`4 onRequestAsync) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Stratum/StratumConnection.cs:line 279

**Comment by lurchinms** [comment]
RTM :

[2022-09-29 06:39:46.1184] [E] [rtm] [0HML21RKCCIRT] Connection error: System.DllNotFoundException: Unable to load shared library 'libcryptonight' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibcryptonight: cannot open shared object file: No such file or directory
   at Miningcore.Native.Cryptonight.alloc_context()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.LazyHelper.ThrowException()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Miningcore.Native.Cryptonight.Context.get_Handle() in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Native/Cryptonight.cs:line 142
   at Miningcore.Native.Cryptonight.CryptonightHash(ReadOnlySpan`1 data, Span`1 result, Algorithm algo, UInt64 height) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Native/Cryptonight.cs:line 192
   at Miningcore.Crypto.Hashing.Algorithms.Ghostrider.Digest(ReadOnlySpan`1 data, Span`1 result, Object[] extra) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Crypto/Hashing/Algorithms/Ghostrider.cs:line 11
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.ProcessShareInternal(StratumConnection worker, String extraNonce2, UInt32 nTime, UInt32 nonce, Nullable`1 versionBits) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 321
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.ProcessShare(StratumConnection worker, String extraNonce2, String nTime, String nonce, String versionBits) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 674
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManager.SubmitShareAsync(StratumConnection worker, Object submission, CancellationToken ct) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 241
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnSubmitAsync(StratumConnection connection, Timestamped`1 tsRequest, CancellationToken ct) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 184
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnRequestAsync(StratumConnection connection, Timestamped`1 tsRequest, CancellationToken ct) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 459
   at Miningcore.Stratum.StratumServer.OnRequestAsync(StratumConnection connection, JsonRpcRequest request, CancellationToken ct) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Stratum/StratumServer.cs:line 203
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func`4 onRequestAsync, ReadOnlySequence`1 lineBuffer) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Stratum/StratumConnection.cs:line 377
   at Miningcore.Stratum.StratumConnection.ProcessRequestAsync(CancellationToken ct, Func`4 onRequestAsync, ReadOnlySequence`1 lineBuffer) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Stratum/StratumConnection.cs:line 377
   at Miningcore.Stratum.StratumConnection.ProcessReceivePipeAsync(CancellationToken ct, TcpProxyProtocolConfig proxyProtocol, Func`4 onRequestAsync) in /home/kriptokyng/miningcore_kriptokyng/src/Miningcore/Stratum/StratumConnection.cs:line 279

**Comment by totom9000** [comment]
Think you need take this with kryptokyng that made your MC version.  Gr works No problem on MC

**Comment by lurchinms** [comment]
Current version doesn't work.

**Comment by jvxis** [comment]
I've been using version 73 and it is working very well.
