### ISSUE TITLE
Block Confirmations Stuck using dev branch

### ISSUE THREAD

**Issue by minershaven** [oliverw/miningcore#1462]
**Describe the bug**
Block confirmations and payouts sometimes get stuck

**To Reproduce**
Normal mining on various coins

**Expected behavior**
normal block confirmations and payouts. 

**Screenshots**
![image](https://user-images.githubusercontent.com/57435138/194714795-592df96d-4312-49dc-848e-00356755975e.png)

**Desktop (please complete the following information):**
 - Ubuntu 18
 

It's only happened once and after i fixed it i never had any other issues but still haven't figured out what caused the issue.  When looking through the logs i found the error
```
[2022-10-07 19:59:13.2219] [E] [PayoutManager] Payment processing failed Npgsql.PostgresException (0x80004005): 22012: division by zero
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
```
after seeing that i opened up postgress and saw that none of the affected blocks had a round effort applied to them and were marked as NULL instead.  

![unknown](https://user-images.githubusercontent.com/57435138/194715061-13780889-ac40-4534-8501-7cd073d41421.png)

To fix it i manually calculated and entered the round effort for each block into the database.  Once it was in there the coins that were still unconfirmed started the confirmation process and the ones that were already confirmed just paid out in one big payment to all the miners.  So far I haven't had any other issues with it but wanted to report it in case someone else runs into the issue they can easily correct it.  I still haven't figured out exactly what caused the glitch or if it was just some random fluke but will look into it more

**Comment by oliverw** [comment]
Looks like the round-effort feature (https://github.com/oliverw/miningcore/pull/1457) which was backported from some other fork is causing problems.

**Comment by minershaven** [comment]
It happened on 2 coins that both found blocks within a second or so of each other and i had to manually fix both. I will keep watching and if it happens again I will try to take a deeper look to see what triggered it.  Other than that 1 hiccup it's been running beautifully for a couple days with a decent amount of miners going. I didn't make any code changes to fix it, simply entered the info into so maybe it was a random glitch.  Just looking to see if anyone else had a similar issue.

**Comment by jon4hz** [comment]
> Looks like the round-effort feature (#1457) which was backported from some other fork is causing problems.

How so? There is no data manipulation in this feature, all it does is reading data from the db. The logs also clearly state, that the error is caused by the payout manager and not from the API. 
Beside the fact that this change isn't even released yet. So unless @minershaven compiled miningcore based on the dev branch, he doesn't even have this feature yet. 

It would be interesting to know which lines actually causes the zero division error and which pools are affected.

**Comment by oliverw** [comment]
> > Looks like the round-effort feature (#1457) which was backported from some other fork is causing problems.
> 
> 
> 
> How so? There is no data manipulation in this feature, all it does is reading data from the db. The logs also clearly state, that the error is caused by the payout manager and not by the API. 
> 
> Beside the fact that this change isn't even released yet. So unless @minershaven compiled miningcore based on the dev branch in the last 2 days, he doesn't even have this feature yet. 
> 
> 
> 
> It would be interesting to know which lines actually causes the zero division error and which pools are affected. 

Yeah I've checked the code and the division by zero error must be caused by the networkdifficulty column being 0, which is quite strange.

**Comment by minershaven** [comment]
> 

I do have that version. Cloned it after yours and my PR's were merged with it. Our pool has found 100+ blocks across multiple coins since and it's working fine. The 2 coins affected were thoon and obtc. I will reply again with the full output from debug log shortly when I'm back at my computer.

**Comment by minershaven** [comment]
> 

@oliverw the difficulty  was around 0.0003.  the 2nd column in the above screenshot.  all the 0's are the confirmation process.

**Comment by minershaven** [comment]
> > Looks like the round-effort feature (#1457) which was backported from some other fork is causing problems.
> 
> How so? There is no data manipulation in this feature, all it does is reading data from the db. The logs also clearly state, that the error is caused by the payout manager and not by the API. Beside the fact that this change isn't even released yet. So unless @minershaven compiled miningcore based on the dev branch in the last 2 days, he doesn't even have this feature yet.
> 
> It would be interesting to know which lines actually causes the zero division error and which pools are affected.

full log below 

```
[2022-10-07 19:59:13.2219] [E] [PayoutManager] Payment processing failed Npgsql.PostgresException (0x80004005): 22012: division by zero
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 473
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/miningcore/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 30
   at Miningcore.Payments.PayoutManager.CalculateBlockEffortAsync(IMiningPool pool, PoolConfig poolConfig, Block block, IPayoutHandler handler, CancellationToken ct) in /home/miningcore/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 240
   at Miningcore.Payments.PayoutManager.<>c__DisplayClass17_1.<<UpdatePoolBalancesAsync>b__4>d.MoveNext() in /home/miningcore/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 167
--- End of stack trace from previous location ---
   at Miningcore.Extensions.ConnectionFactoryExtensions.RunTx(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /home/miningcore/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 61
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig poolConfig, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /home/miningcore/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 164
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /home/miningcore/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 104
  Exception data:
    Severity: ERROR
    SqlState: 22012
    MessageText: division by zero
    File: float.c
    Line: 104
    Routine: float_zero_divide_error    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 473
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/miningcore/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 30
   at Miningcore.Payments.PayoutManager.CalculateBlockEffortAsync(IMiningPool pool, PoolConfig poolConfig, Block block, IPayoutHandler handler, CancellationToken ct) in /home/miningcore/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 240
   at Miningcore.Payments.PayoutManager.<>c__DisplayClass17_1.<<UpdatePoolBalancesAsync>b__4>d.MoveNext() in /home/miningcore/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 167
--- End of stack trace from previous location ---
   at Miningcore.Extensions.ConnectionFactoryExtensions.RunTx(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /home/miningcore/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 61
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig poolConfig, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /home/miningcore/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 164
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /home/miningcore/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 104
```
