### ISSUE TITLE
Unable to load shared library 'libethhash'

### ISSUE THREAD

**Issue by n128au** [oliverw/miningcore#1506]
I tried to setup eth pool but it gives an error, there was no such error with other coins.

[2022-11-13 21:59:32.2239] [I] [ETH1] ExtraNonceProvider using 4 bits for instance id, 12 bits for 4095 values, instance id = 0x9
[2022-11-13 21:59:32.2295] [E] [ETH1] System.DllNotFoundException: Unable to load shared library 'libethhash' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibethhash: cannot open shared object file: No such file or directory System.DllNotFoundException: Unable to load shared library 'libethhash' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibethhash: cannot open shared object file: No such file or directory
   at Miningcore.Native.EthHash.ethash_get_default_dirname(Byte* data, Int32 length)
   at Miningcore.Crypto.Hashing.Ethash.Dag.GetDefaultDagDirectory() in /root/miningcore_kriptokyng/src/Miningcore/Crypto/Hashing/Ethash/Dag.cs:line 35
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.Configure(PoolConfig pc, ClusterConfig cc) in /root/miningcore_kriptokyng/src/Miningcore/Blockchain/Ethereum/EthereumJobManager.cs:line 349
   at Miningcore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationToken ct) in /root/miningcore_kriptokyng/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs:line 373
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /root/miningcore_kriptokyng/src/Miningcore/Mining/PoolBase.cs:line 392    at Miningcore.Native.EthHash.ethash_get_default_dirname(Byte* data, Int32 length)
   at Miningcore.Crypto.Hashing.Ethash.Dag.GetDefaultDagDirectory() in /root/miningcore_kriptokyng/src/Miningcore/Crypto/Hashing/Ethash/Dag.cs:line 35
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.Configure(PoolConfig pc, ClusterConfig cc) in /root/miningcore_kriptokyng/src/Miningcore/Blockchain/Ethereum/EthereumJobManager.cs:line 349
   at Miningcore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationToken ct) in /root/miningcore_kriptokyng/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs:line 373
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /root/miningcore_kriptokyng/src/Miningcore/Mining/PoolBase.cs:line 392
[2022-11-13 21:59:32.2736] [I] [Lifetime] Application is shutting down...
System.DllNotFoundException: Unable to load shared library 'libethhash' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibethhash: cannot open shared object file: No such file or directory
   at Miningcore.Program.<>c__DisplayClass17_0.<ExecuteAsync>b__1(Exception ex) in /root/miningcore_kriptokyng/src/Miningcore/Program.cs:line 384
   at Miningcore.Util.ActionUtils.Guard(Func`1 func, Action`1 errorHandler) in /root/miningcore_kriptokyng/src/Miningcore/Util/ActionUtils.cs:line 14
   at Miningcore.Program.ExecuteAsync(CancellationToken ct) in /root/miningcore_kriptokyng/src/Miningcore/Program.cs:line 368
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Miningcore.Program.Main(String[] args) in /root/miningcore_kriptokyng/src/Miningcore/Program.cs:line 245
Cluster cannot start. Good Bye!

**Comment by jon4hz** [comment]
Looks like you're using the fork https://github.com/lurchinms/miningcore_kriptokyng which has some changes in the build system. Try to open an issue there.
