### ISSUE TITLE
ecash (XEC) reject blocks with bad-cb-minerfund error

### ISSUE THREAD

**Issue by oliverw** [oliverw/miningcore#1542]
### Discussed in https://github.com/oliverw/miningcore/discussions/1541

<div type='discussions-op-text'>

<sup>Originally posted by **btclinux** December  8, 2022</sup>
Hi! I see in coins.json for ecash https://github.com/oliverw/miningcore/blob/master/src/Miningcore/coins.json#L908
```"hasMinerFund": true```

All blocks rejected with:
```
ERROR: ConnectTip: ConnectBlock 0000000000000000097c03ca368bc4efbc271a1ba308877befdf69d62cdb3a5c failed, bad-cb-minerfund
```
Should I add something special in pool config?

ecash node config:
```
rpcuser=rpcuser
rpcpassword=rpcpassword
prune=550
deprecatedrpc=accounts
usecashaddr=0
zmqpubhashblock=tcp://127.0.0.1:15101
```</div>

**Comment by goodthebest** [comment]
probably, it would give some idea 

https://bitcoinabc.org/doc/dev/validation_8cpp_source.html

![image](https://user-images.githubusercontent.com/1715740/207367261-abccb1ee-294a-491f-9fc4-425c6afa0233.png)

**Comment by btclinux** [comment]
Hi! I think I found a problem.
If using 'usecashaddr=1' and 'ecash=0' in node config we get minerfund address bitcoincash:prfhcnyqnl5cgrnmlfmms675w93ld7mvvq5zsvycff which we can see here https://github.com/Bitcoin-ABC/bitcoin-abc/blob/47a114b9882b15e62e53d2c9ad90ce96808ea30d/src/minerfund.cpp#L40
But pool not starting due base58 check
```
[2023-01-19 10:17:51.9798] [E] [ecash] Error during UpdateJob System.FormatException: Invalid base58 data
   at NBitcoin.DataEncoders.Base58Encoder.DecodeData(String encoded)
   at NBitcoin.DataEncoders.Base58CheckEncoder.DecodeData(String encoded)
   at Miningcore.Blockchain.Bitcoin.BitcoinUtils.AddressToDestination(String address, Network expectedNetwork) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinUtils.cs:line 20
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.CreateMinerFundOutputs(Transaction tx, Money reward) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 534
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.CreateOutputTransaction() in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 250
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.BuildCoinbase() in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 91
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.Init(BlockTemplate blockTemplate, String jobId, PoolConfig pc, BitcoinPoolConfigExtra extraPoolConfig, ClusterConfig cc, IMasterClock clock, IDestination poolAddressDestination, Network network, Boolean isPoS, Double shareMultiplier, IHashAlgorithm coinbaseHasher, IHashAlgorithm headerHasher, IHashAlgorithm blockHasher) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 639                   
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManager.UpdateJob(CancellationToken ct, Boolean forceUpdate, String via, String json)    at NBitcoin.DataEncoders.Base58Encoder.DecodeData(String encoded)
   at NBitcoin.DataEncoders.Base58CheckEncoder.DecodeData(String encoded)
   at Miningcore.Blockchain.Bitcoin.BitcoinUtils.AddressToDestination(String address, Network expectedNetwork) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinUtils.cs:line 20
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.CreateMinerFundOutputs(Transaction tx, Money reward) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 534
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.CreateOutputTransaction() in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 250
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.BuildCoinbase() in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 91
   at Miningcore.Blockchain.Bitcoin.BitcoinJob.Init(BlockTemplate blockTemplate, String jobId, PoolConfig pc, BitcoinPoolConfigExtra extraPoolConfig, ClusterConfig cc, IMasterClock clock, IDestination poolAddressDestination, Network network, Boolean isPoS, Double shareMultiplier, IHashAlgorithm coinbaseHasher, IHashAlgorithm headerHasher, IHashAlgorithm blockHasher) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 639                   
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManager.UpdateJob(CancellationToken ct, Boolean forceUpdate, String via, String json)
```

If using 'usecashaddr=0' in node config we get minerfund address 3LyFQTKbPwXtgrsGpMbbEECY7ViBeFbonU in block template which is not presented in ABC source code.
Any suggestions?

**Comment by oliverw** [comment]
> Hi! I think I found a problem. If using 'usecashaddr=1' and 'ecash=0' in node config we get minerfund address bitcoincash:prfhcnyqnl5cgrnmlfmms675w93ld7mvvq5zsvycff which we can see here https://github.com/Bitcoin-ABC/bitcoin-abc/blob/47a114b9882b15e62e53d2c9ad90ce96808ea30d/src/minerfund.cpp#L40 But pool not starting due base58 check
> 
> ```
> [2023-01-19 10:17:51.9798] [E] [ecash] Error during UpdateJob System.FormatException: Invalid base58 data
>    at NBitcoin.DataEncoders.Base58Encoder.DecodeData(String encoded)
>    at NBitcoin.DataEncoders.Base58CheckEncoder.DecodeData(String encoded)
>    at Miningcore.Blockchain.Bitcoin.BitcoinUtils.AddressToDestination(String address, Network expectedNetwork) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinUtils.cs:line 20
>    at Miningcore.Blockchain.Bitcoin.BitcoinJob.CreateMinerFundOutputs(Transaction tx, Money reward) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 534
>    at Miningcore.Blockchain.Bitcoin.BitcoinJob.CreateOutputTransaction() in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 250
>    at Miningcore.Blockchain.Bitcoin.BitcoinJob.BuildCoinbase() in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 91
>    at Miningcore.Blockchain.Bitcoin.BitcoinJob.Init(BlockTemplate blockTemplate, String jobId, PoolConfig pc, BitcoinPoolConfigExtra extraPoolConfig, ClusterConfig cc, IMasterClock clock, IDestination poolAddressDestination, Network network, Boolean isPoS, Double shareMultiplier, IHashAlgorithm coinbaseHasher, IHashAlgorithm headerHasher, IHashAlgorithm blockHasher) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 639                   
>    at Miningcore.Blockchain.Bitcoin.BitcoinJobManager.UpdateJob(CancellationToken ct, Boolean forceUpdate, String via, String json)    at NBitcoin.DataEncoders.Base58Encoder.DecodeData(String encoded)
>    at NBitcoin.DataEncoders.Base58CheckEncoder.DecodeData(String encoded)
>    at Miningcore.Blockchain.Bitcoin.BitcoinUtils.AddressToDestination(String address, Network expectedNetwork) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinUtils.cs:line 20
>    at Miningcore.Blockchain.Bitcoin.BitcoinJob.CreateMinerFundOutputs(Transaction tx, Money reward) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 534
>    at Miningcore.Blockchain.Bitcoin.BitcoinJob.CreateOutputTransaction() in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 250
>    at Miningcore.Blockchain.Bitcoin.BitcoinJob.BuildCoinbase() in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 91
>    at Miningcore.Blockchain.Bitcoin.BitcoinJob.Init(BlockTemplate blockTemplate, String jobId, PoolConfig pc, BitcoinPoolConfigExtra extraPoolConfig, ClusterConfig cc, IMasterClock clock, IDestination poolAddressDestination, Network network, Boolean isPoS, Double shareMultiplier, IHashAlgorithm coinbaseHasher, IHashAlgorithm headerHasher, IHashAlgorithm blockHasher) in /home/pool/miningcore-test/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs:line 639                   
>    at Miningcore.Blockchain.Bitcoin.BitcoinJobManager.UpdateJob(CancellationToken ct, Boolean forceUpdate, String via, String json)
> ```
> 
> If using 'usecashaddr=0' in node config we get minerfund address 3LyFQTKbPwXtgrsGpMbbEECY7ViBeFbonU in block template which is not presented in ABC source code. Any suggestions?

Very interesting. Working on it.

**Comment by jon4hz** [comment]
Adding `"addressType": "bcash"` to the pool config should allow you to use the bech32 cash address.

**Comment by btclinux** [comment]
> Adding `"addressType": "bcash"` to the pool config should allow you to use the bech32 cash address.

I did, and got "Error during UpdateJob System.FormatException: Invalid base58 data"

**Comment by furcalor** [comment]
Currently NBitcoin does not seem to like the minerfund address. Even if you add ecash support to nbitcoin the minerfund address seems to still fail to decode correctly.

**Comment by btclinux** [comment]
> Currently NBitcoin does not seem to like the minerfund address. Even if you add ecash support to nbitcoin the minerfund address seems to still fail to decode correctly.

Minerfund have a bitcoincash: format, not ecash:

**Comment by furcalor** [comment]
> 

You have it working with bitcoincash: instead of ecash:  and the minderfund is set and decoded correctly?
