### ISSUE TITLE
Invalid base58 data

### ISSUE THREAD

**Issue by l-urk** [oliverw/miningcore#1560]
Running miningcore on windows with postgresSQL database already set up.
When running miningcore with dotnet run after some success I get

[E] [bitcoin] System.FormatException: Invalid base58 data System.FormatException: Invalid base58 data

Here is the entire readout

Using configuration file '..\..\..\config.json'
[2022-12-25 21:15:23.2388] [I] [Core] Version 74.0.0.0-master [171a262a3f7861bbb54178d385806b9afebcb0af]
[2022-12-25 21:15:23.2657] [I] [Core] Runtime .NET 6.0.11 on Microsoft Windows 10.0.19045 [X64]
[2022-12-25 21:15:23.3582] [I] [Core] Prometheus Metrics API listening on http://127.0.0.1:4000/metrics
[2022-12-25 21:15:23.3582] [I] [Core] WebSocket Events streaming on ws://127.0.0.1:4000/notifications
[2022-12-25 21:15:25.5814] [I] [ShareRecorder] Online
[2022-12-25 21:15:25.6324] [I] [PayoutManager] Online
[2022-12-25 21:15:25.6324] [I] [StatsRecorder] Online
[2022-12-25 21:15:25.9403] [I] [Core] 120 coins loaded from 'C:\Users\l_\miningcore\src\Miningcore\bin\Debug\net6.0\coins.js
[2022-12-25 21:15:25.9634] [I] [bitcoin] Starting Pool ...
[2022-12-25 21:15:25.9634] [I] [bitcoin] ExtraNonceProvider using 4 bits for instance id, 28 bits for 268435455 values, inst
[2022-12-25 21:15:25.9734] [I] [bitcoin] Starting Job Manager ...
[2022-12-25 21:15:26.0886] [I] [bitcoin] All daemons online
[2022-12-25 21:15:26.1695] [I] [Core] API Access to /api/admin restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2022-12-25 21:15:26.1695] [I] [Core] API Access to /metrics restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2022-12-25 21:15:26.2331] [I] [bitcoin] All daemons synched with blockchain
[2022-12-25 21:15:26.2712] [E] [bitcoin] System.FormatException: Invalid base58 data System.FormatException: Invalid base58
   at NBitcoin.DataEncoders.Base58Encoder.DecodeData(String encoded)
   at NBitcoin.DataEncoders.Base58CheckEncoder.DecodeData(String encoded)
   at Miningcore.Blockchain.Bitcoin.BitcoinUtils.AddressToDestination(String address, Network expectedNetwork) in C:\Users\l
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AddressToDestination(String address, Nullable`1 addressType) in
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.PostStartInitAsync(CancellationToken ct) in C:\Users\l_\miningco
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in C:\Users\l_\miningcore\src\Miningcore\Block
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in C:\Users\l_\miningcore\src\Miningco
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in C:\Users\l_\miningcore\src\Miningcore\Mining\PoolBase.cs:
   at NBitcoin.DataEncoders.Base58CheckEncoder.DecodeData(String encoded)
   at Miningcore.Blockchain.Bitcoin.BitcoinUtils.AddressToDestination(String address, Network expectedNetwork) in C:\Users\l
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AddressToDestination(String address, Nullable`1 addressType) in
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.PostStartInitAsync(CancellationToken ct) in C:\Users\l_\miningco
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in C:\Users\l_\miningcore\src\Miningcore\Block
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in C:\Users\l_\miningcore\src\Miningco
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in C:\Users\l_\miningcore\src\Miningcore\Mining\PoolBase.cs:
[2022-12-25 21:15:26.3574] [I] [Lifetime] Application is shutting down...
[2022-12-25 21:15:26.3574] [I] [Core] API access limited to 5 requests per 1s, except from 127.0.0.1, ::1, ::ffff:127.0.0.1

**Comment by l-urk** [comment]
To clarify. This is only a problem when attempting to run a pool with Bitcoin. I just tried Litecoin and it works fine.

**Comment by seperatis** [comment]
@l-urk check the BTC address.....you **_may_** still need to use a Legacy address (not sure if other addresses have been supported yet).

`bitcoin-cli getnewaddress "" "legacy"`

**Comment by l-urk** [comment]
@seperatis This worked, thanks so much
